version: '2'
services:

  ## Shards
  shard03a:
    image: mongo:4.4.1
    command: mongod --port 8081 --shardsvr --bind_ip_all --replSet shard03 --dbpath /data/db --oplogSize 16 --auth --keyFile /mongodb.key
    volumes:
      - ./mongodb.key:/mongodb.key
      - ./scripts:/scripts
    ports:
      - "8081:8081"
    networks:
      - all
  shard03b:
    image: mongo:4.4.1
    command: mongod --port 8082 --shardsvr --bind_ip_all --replSet shard03 --dbpath /data/db --oplogSize 16 --auth --keyFile /mongodb.key
    volumes:
      - ./mongodb.key:/mongodb.key
      - ./scripts:/scripts
    ports:
      - "8082:8082"
    networks:
      - all

networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16