version: '2'
services:

  ## Shards
  shard01a:
    image: mongo:4.4.1
    command: mongod --auth --port 27018 --shardsvr --replSet shard01 --dbpath /data/db --oplogSize 16 --keyFile /mongodb.key
    volumes:
      - ./mongodb.key:/mongodb.key
      - ./scripts:/scripts
    networks:
      - all
  shard01b:
    image: mongo:4.4.1
    command: mongod --auth --port 27018 --shardsvr --replSet shard01 --dbpath /data/db --oplogSize 16 --keyFile /mongodb.key
    volumes:
      - ./mongodb.key:/mongodb.key
      - ./scripts:/scripts
    networks:
      - all
      
networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16