version: '2'
services:

  ## Config Servers
  config01:
    image: mongo:4.4.1
    command: mongod --auth --port 8082 --configsvr --replSet configserver --dbpath /data/db --oplogSize 16 --keyFile /mongodb.key
    ports:
      - "8082:8082"
    volumes:
      - ./mongodb.key:/mongodb.key
      - ./scripts:/scripts
    networks:
      - all
  config02:
    image: mongo:4.4.1
    command: mongod --auth --port 8083 --configsvr --replSet configserver --dbpath /data/db --oplogSize 16 --keyFile /mongodb.key
    ports:
      - "8083:8083"
    volumes:
      - ./mongodb.key:/mongodb.key
      - ./scripts:/scripts
    networks:
      - all
  config03:
    image: mongo:4.4.1
    command: mongod --auth --port 8084 --configsvr --replSet configserver --dbpath /data/db --oplogSize 16 --keyFile /mongodb.key
    ports:
      - "8084:8084"
    volumes:
      - ./mongodb.key:/mongodb.key
      - ./scripts:/scripts
    networks:
      - all

  ## Router
  router:
    image: mongo:4.4.1
    command: mongos --port 8081 --configdb configserver/172.27.150.39:8082,172.27.150.39:8083,172.27.150.39:8084 --bind_ip_all --keyFile /mongodb.key
    ports:
      - "8081:8081"
    volumes:
      - ./mongodb.key:/mongodb.key
      - ./scripts:/scripts
    depends_on:
      - config01
      - config02
      - config03
    networks:
      - all

networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16