version: '2'
services:

  ## Config Servers
  config01:
    image: mongo:4.4.1
    command: mongod --auth --port 27017 --configsvr --replSet configserver --dbpath /data/db --oplogSize 16 --keyFile /mongodb.key
    volumes:
      - ./mongodb.key:/mongodb.key
      - ./scripts:/scripts
    networks:
      - all
  config02:
    image: mongo:4.4.1
    command: mongod --auth --port 27017 --configsvr --replSet configserver --dbpath /data/db --oplogSize 16 #--keyFile /mongodb.key
    volumes:
      - ./mongodb.key:/mongodb.key
      - ./scripts:/scripts
    networks:
      - all
  config03:
    image: mongo:4.4.1
    command: mongod --auth --port 27017 --configsvr --replSet configserver --dbpath /data/db --oplogSize 16 #--keyFile /mongodb.key
    volumes:
      - ./mongodb.key:/mongodb.key
      - ./scripts:/scripts
    networks:
      - all

  ## Router
  router:
    image: mongo:4.4.1
    command: mongos --port 8081 --configdb configserver/config01:27017,config02:27017,config03:27017 --bind_ip_all # --keyFile /mongodb.key
    ports:
      - "8081:8081"
    volumes:
      - ./mongodb.key:/mongodb.key
      - ./scripts:/scripts
    depends_on:
      - config01
      - config02
      - config03
    networks:
      - all

networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16